version: '3.9'

services:

  dotnet_backend:
    container_name: dotnet_backend
    build:
      context: FileStorageApp/
      dockerfile: Dockerfile
      target: runtime_FileStorageAPI
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5001
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - '5001:5001'
        
  dotnet_search_backend:
    container_name: dotnet_search_backend
    build:
      context: FileStorageApp/
      dockerfile: Dockerfile
      target: runtime_SearchDocumentsAPI
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5002
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - '5002:5002'

  front:
    container_name: front
    build:
      context: file-storage-front/
      dockerfile: Dockerfile
      target: start_prod
    ports:
      - '3000:3000'

  telegram_auth:
    container_name: telegram_auth
    build:
      context: FileStorageApp/
      dockerfile: TelegramAuth/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release


  telegram_loader:
    container_name: telegram_loader
    build:
      context: telegram_file_loader/
      dockerfile: Dockerfile
    environment:
      - Test="false"
      - DB_HOST=31.184.208.123
      - DB_PORT=5432
      - DB_NAME=filestore
      - DB_USER=filestore
      - DB_PASS=mlonDNBDFPqC
      - S3_URL=http://students.66bit.ru:19000
      - BUCKET_NAME=filestore
    ports:
      - '8080:8080'
    depends_on:
      - front
      - dotnet_backend
